# WebWeaver 默认配置文件

# 智能体配置
agents:
  planner:
    max_iterations: 5
    completeness_threshold: 0.8
    outline_optimization_threshold: 0.7
    quality_check: true
  
  writer:
    max_section_length: 2000
    citation_validation: true
    quality_check: true
    style_consistency: true

# 记忆库配置
memory_bank:
  max_evidence_count: 1000
  similarity_threshold: 0.7
  indexing_strategy: "semantic"
  auto_cleanup: true
  cleanup_threshold: 0.8

# 搜索引擎配置
search_engines:
  web:
    enabled: true
    api_key: ""
    base_url: "https://api.search.com/v1/search"
    max_results: 20
    timeout: 10
  
  academic:
    enabled: true
    api_key: ""
    base_url: "https://api.semanticscholar.org/graph/v1/paper/search"
    max_results: 15
    timeout: 10
  
  mock:
    enabled: false
    mock_results: []

# 网页抓取配置
web_scraper:
  timeout: 10
  max_retries: 3
  delay_range: [1, 3]
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  max_content_length: 50000
  follow_redirects: true

# 内容处理配置
content_processor:
  max_keywords: 10
  summary_length: 200
  readability_check: true
  language_detection: true

# 引用管理配置
citation_manager:
  default_format: "apa"
  auto_validate: true
  max_citations: 100
  citation_styles: ["apa", "mla", "chicago", "ieee"]

# LLM配置
llm:
  model: "gpt-4"
  temperature: 0.7
  max_tokens: 4000
  api_key: ""
  base_url: ""
  timeout: 30
  retry_attempts: 3

# 研究配置
research:
  max_iterations: 5
  min_evidence_count: 10
  max_evidence_count: 100
  quality_threshold: 0.7
  completeness_threshold: 0.8

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/webweaver.log"
  max_file_size: "10MB"
  backup_count: 5

# 性能配置
performance:
  parallel_processing: true
  max_workers: 4
  cache_enabled: true
  cache_ttl: 3600
  memory_limit: "1GB"

# 安全配置
security:
  rate_limiting: true
  max_requests_per_minute: 60
  allowed_domains: []
  blocked_domains: []
  content_filtering: true

# 评估配置
evaluation:
  auto_evaluate: true
  evaluation_threshold: 0.7
  quality_metrics: ["accuracy", "completeness", "citation_quality"]
  detailed_report: true
